markdown: kramdown
highlighter: rouge
sass:
  style: compressed

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

repository: https://github.com/xanadu31/dataddiction.github.io

timezone: America/Los_Angeles

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "news_item"
      image: /img/twitter-card.png

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: Dataddiction
description: Data Science with R, Python and Scala.
url: https://dataddiction.github.io

twitter:
  username: xanadu310

logo: /img/logo-2x.png

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - CNAME
  - icomoon-selection.json
  - readme.md
